name: Build and push all the software images
run-name: ${{ github.actor }} has triggered a build 🚀
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: isv-managed-starburst-operator
  IMAGE_REGISTRY: quay.io
  REGISTRY_USER: sughosh
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  BUILD_VERSION: v0.69.0
jobs:
  build-image-and-push-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.4'
    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}
    - name: Setup operator-sdk
      run: |
        cd ~/
        export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac)
        export OS=$(uname | awk '{print tolower($0)}')
        export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/latest/download
        curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}
        chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk
        operator-sdk version
    - name: Build and publish docker image
      run: |
        cd ${GITHUB_WORKSPACE}
        IMAGE_FULL=${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_VERSION }}
        echo IMAGE_FULL variable is: ${IMAGE_FULL}
        echo Build and Push operator image: ${IMAGE_FULL}
        make docker-build docker-push IMG="${IMAGE_FULL}"
        echo Making operator bundle
        make bundle IMG="${IMAGE_FULL}:${{ env.BUILD_VERSION }}" CHANNELS="alpha" DEFAULT_CHANNEL="alpha" VERSION="${{ env.BUILD_VERSION }}"
        echo Build and Push operator bundle image: ${IMAGE_FULL}-bundle
        make bundle-build bundle-push BUNDLE_IMG=${IMAGE_FULL}-bundle:${{ env.BUILD_VERSION }}"
